# This file was generated by GoReleaser. DO NOT EDIT.
cask "openfeed" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b58d197c332047cfda265d478fe2623c155fcd9b7e35f26eb44eaf075536184f"
      url "https://github.com/JoshuaFurman/openfeed/releases/download/v#{version}/openfeed_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9408fac9fdc1cf2603a301b7767d19bbd5330842ee48ba0bd41722339ec64f2"
      url "https://github.com/JoshuaFurman/openfeed/releases/download/v#{version}/openfeed_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "962bf8a30201bd9a963cb1829f0345dfa2691835f5cd7c926a6ddfc760e40775"
      url "https://github.com/JoshuaFurman/openfeed/releases/download/v#{version}/openfeed_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a45f2f3f1842362cd660025f7eb6a173c2d23a306981b166d3cd4ba6c3aa430"
      url "https://github.com/JoshuaFurman/openfeed/releases/download/v#{version}/openfeed_#{version}_linux_amd64.tar.gz"
    end
  end

  name "openfeed"
  desc "A TUI-first RSS reader with the feel of a chronological timeline"
  homepage "https://github.com/JoshuaFurman/openfeed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openfeed"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/openfeed"]
    end
  end

  # No zap stanza required
end
